module.exports = {
  // 默认情况下，文档龙从文档文件夹结构生成侧边栏
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // 但是您可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}
