/*******************************************************************************
 * Copyright (c) 2023 慧科云
 * 此源代码根据 MIT 许可证进行许可，该许可证位于此源代码树根目录中的 LICENSE 文件中。
 * 最后修改时间：2023/4/7 上午10:50
 ******************************************************************************/

module.exports = {
  // 默认情况下，文档龙从文档文件夹结构生成侧边栏
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // 但是您可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}
